[project]
name = "data-visualization-notebooks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "polars>=1.33.0",
    "pyarrow>=21.0.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
